management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown: #\u5173\u95ED\u7AEF\u70B9
      enabled: true


#\u9996\u9875\u9762\uFF1Ahttp://localhost:8080/actuator
#\u5065\u5EB7\u72B6\u51B5\uFF1Ahttp://localhost:8080/actuator/health
